# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.39.0"

default_platform :ios

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :deploy do
    increment_build_number
    commit_version_bump
    add_git_tag
    push_to_git_remote

    gym(scheme: "22") # Build your app - more options available

    sigh
    snapshot

    deliver
  end

  desc "Deploy a new version to the App Store"
  lane :snapshot do
    snapshot
  end
end
